// packages/react/src/Globe.tsx
import {
  forwardRef,
  useEffect,
  useImperativeHandle,
  useLayoutEffect,
  useRef,
  type CSSProperties,
  type ForwardedRef,
} from 'react';
import {
  createGlobe,
  type CountryEvent,
  type GlobeConfig,
  type GlobeInstance,
  type LatLng,
  type MarkerConfig,
  type MarkerEvent,
} from '@your-globe/core';

export type GlobeProps = Omit<GlobeConfig, 'container'> & {
  readonly className?: string;
  readonly style?: CSSProperties;
  readonly onCountryClick?: (event: CountryEvent) => void;
  readonly onCountryHover?: (event: CountryEvent | null) => void;
  readonly onMarkerClick?: (event: MarkerEvent) => void;
  readonly onMarkerHover?: (event: MarkerEvent | null) => void;
  readonly onReady?: () => void;
  readonly onError?: (error: Error) => void;
};

export interface GlobeHandle {
  readonly setRotation: (position: LatLng, animate?: boolean) => void;
  readonly setMarkers: (markers: ReadonlyArray<MarkerConfig>) => void;
  readonly addMarker: (marker: MarkerConfig) => void;
  readonly removeMarker: (id: string) => void;
  readonly resize: () => void;
  readonly getCanvas: () => HTMLCanvasElement | null;
}

const DEFAULT_STYLE: CSSProperties = { width: '100%', height: '100%' };

const GlobeComponent = (props: GlobeProps, ref: ForwardedRef<GlobeHandle>): JSX.Element => {
  const {
    className,
    style,
    onCountryClick,
    onCountryHover,
    onMarkerClick,
    onMarkerHover,
    onReady,
    onError,
    ...config
  } = props;

  const containerRef = useRef<HTMLDivElement>(null);
  const instanceRef = useRef<GlobeInstance | null>(null);
  const handlersRef = useRef({ onCountryClick, onCountryHover, onMarkerClick, onMarkerHover, onReady, onError });

  handlersRef.current = { onCountryClick, onCountryHover, onMarkerClick, onMarkerHover, onReady, onError };

  useLayoutEffect(() => {
    const container = containerRef.current;
    if (!container) return undefined;

    const instance = createGlobe({ container, ...config });
    instanceRef.current = instance;

    const offCountryClick = instance.on('countryClick', (e) => handlersRef.current.onCountryClick?.(e));
    const offCountryHover = instance.on('countryHover', (e) => handlersRef.current.onCountryHover?.(e));
    const offMarkerClick = instance.on('markerClick', (e) => handlersRef.current.onMarkerClick?.(e));
    const offMarkerHover = instance.on('markerHover', (e) => handlersRef.current.onMarkerHover?.(e));
    const offReady = instance.on('ready', () => handlersRef.current.onReady?.());
    const offError = instance.on('error', (err) => handlersRef.current.onError?.(err));

    instance.mount();

    return () => {
      offCountryClick();
      offCountryHover();
      offMarkerClick();
      offMarkerHover();
      offReady();
      offError();
      instance.destroy();
      instanceRef.current = null;
    };
  }, []);

  useEffect(() => {
    instanceRef.current?.update(config);
  }, [config]);

  useImperativeHandle(
    ref,
    () => ({
      setRotation: (position, animate) => instanceRef.current?.setRotation(position, animate),
      setMarkers: (markers) => instanceRef.current?.setMarkers(markers),
      addMarker: (marker) => instanceRef.current?.addMarker(marker),
      removeMarker: (id) => instanceRef.current?.removeMarker(id),
      resize: () => instanceRef.current?.resize(),
      getCanvas: () => instanceRef.current?.getCanvas() ?? null,
    }),
    []
  );

  return <div ref={containerRef} className={className} style={{ ...DEFAULT_STYLE, ...style }} />;
};

export const Globe = forwardRef<GlobeHandle, GlobeProps>(GlobeComponent);
Globe.displayName = 'Globe';

// packages/angular/src/globe.component.ts
import {
  AfterViewInit,
  ChangeDetectionStrategy,
  Component,
  ElementRef,
  EventEmitter,
  Input,
  NgZone,
  OnChanges,
  OnDestroy,
  Output,
  PLATFORM_ID,
  SimpleChanges,
  ViewChild,
  inject,
} from '@angular/core';
import { isPlatformBrowser } from '@angular/common';
import {
  createGlobe,
  type AtmosphereConfig,
  type AutoRotateConfig,
  type CountriesConfig,
  type CountryEvent,
  type GlobeConfig,
  type GlobeInstance,
  type LatLng,
  type MarkerConfig,
  type MarkerEvent,
  type PerformanceConfig,
} from '@your-globe/core';

@Component({
  selector: 'ng-globe',
  standalone: true,
  template: '<div #host class="globe-host"></div>',
  styles: [':host{display:block;width:100%;height:100%}.globe-host{width:100%;height:100%}'],
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class GlobeComponent implements AfterViewInit, OnChanges, OnDestroy {
  @ViewChild('host', { static: true }) private readonly host!: ElementRef<HTMLDivElement>;

  @Input() public mode: GlobeConfig['mode'];
  @Input() public countries?: CountriesConfig;
  @Input() public markers: ReadonlyArray<MarkerConfig> = [];
  @Input() public atmosphere?: AtmosphereConfig;
  @Input() public autoRotate?: AutoRotateConfig;
  @Input() public performance?: PerformanceConfig;
  @Input() public initialPosition?: LatLng;
  @Input() public minZoom?: number;
  @Input() public maxZoom?: number;

  @Output() public readonly countryClick = new EventEmitter<CountryEvent>();
  @Output() public readonly countryHover = new EventEmitter<CountryEvent | null>();
  @Output() public readonly markerClick = new EventEmitter<MarkerEvent>();
  @Output() public readonly markerHover = new EventEmitter<MarkerEvent | null>();
  @Output() public readonly ready = new EventEmitter<void>();
  @Output() public readonly globeError = new EventEmitter<Error>();

  private readonly platformId = inject(PLATFORM_ID);
  private readonly ngZone = inject(NgZone);
  private instance: GlobeInstance | null = null;

  public ngAfterViewInit(): void {
    if (!isPlatformBrowser(this.platformId)) return;

    this.ngZone.runOutsideAngular(() => {
      const instance = createGlobe({
        container: this.host.nativeElement,
        ...this.buildConfig(),
      });

      instance.on('countryClick', (e) => this.ngZone.run(() => this.countryClick.emit(e)));
      instance.on('countryHover', (e) => this.ngZone.run(() => this.countryHover.emit(e)));
      instance.on('markerClick', (e) => this.ngZone.run(() => this.markerClick.emit(e)));
      instance.on('markerHover', (e) => this.ngZone.run(() => this.markerHover.emit(e)));
      instance.on('ready', () => this.ngZone.run(() => this.ready.emit()));
      instance.on('error', (err) => this.ngZone.run(() => this.globeError.emit(err)));

      instance.mount();
      this.instance = instance;
    });
  }

  public ngOnChanges(changes: SimpleChanges): void {
    if (!this.instance) return;
    const hasRelevantChange = Object.keys(changes).some((key) => !changes[key]?.firstChange);
    if (hasRelevantChange) {
      this.ngZone.runOutsideAngular(() => this.instance?.update(this.buildConfig()));
    }
  }

  public ngOnDestroy(): void {
    this.instance?.destroy();
    this.instance = null;
  }

  public setRotation(position: LatLng, animate?: boolean): void {
    this.instance?.setRotation(position, animate);
  }

  public addMarker(marker: MarkerConfig): void {
    this.instance?.addMarker(marker);
  }

  public removeMarker(id: string): void {
    this.instance?.removeMarker(id);
  }

  public resize(): void {
    this.instance?.resize();
  }

  private buildConfig(): Omit<GlobeConfig, 'container'> {
    return {
      ...(this.mode !== undefined && { mode: this.mode }),
      ...(this.countries !== undefined && { countries: this.countries }),
      markers: this.markers,
      ...(this.atmosphere !== undefined && { atmosphere: this.atmosphere }),
      ...(this.autoRotate !== undefined && { autoRotate: this.autoRotate }),
      ...(this.performance !== undefined && { performance: this.performance }),
      ...(this.initialPosition !== undefined && { initialPosition: this.initialPosition }),
      ...(this.minZoom !== undefined && { minZoom: this.minZoom }),
      ...(this.maxZoom !== undefined && { maxZoom: this.maxZoom }),
    };
  }
}
